server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/




spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - PUT
              - POST
              - PATCH
              - DELETE
              - OPTIONS
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/storage-service/**
          filters:
            - RewritePath=/storage-service/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
        - id: staff-management-service
          uri: lb://staff-management-service
          predicates:
            - Path=/staff-management/**
          filters:
            - RewritePath=/staff-management/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
        - id: product-catalog-service
          uri: lb://product-catalog-service
          predicates:
            - Path=/product-catalog/**
          filters:
            - RewritePath=/product-catalog/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
         


keycloak:
    cors: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
