server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/




spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
        routes:
        - id: storage-service
          uri: lb://storage-service
          predicates:
          - Path=/storage/**
          filters:
          - RewritePath=/storage/(?<path>.*), /$\{path}
          - RemoveRequestHeader= Cookie,Set-Cookie
        - id: staff-management-service
          uri: lb://staff-management-service
          predicates:
          - Path=/staff-management/**
          filters:
          - RewritePath=/staff-management/(?<path>.*), /$\{path}
          - RemoveRequestHeader= Cookie,Set-Cookie


management:
  endpoints:
    web:
      exposure:
        include: "*"
