server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/




spring:
  cloud:
    loadbalancer.ribbon.enabled: false
#    gateway:
#      routes:
#        - id:
#          uri: lb://organization-service
#          predicates:
#            - Path=/organization/**
#          filters:
#            - RewritePath=/organization/(?<path>.*), /$\{path}
#            - RemoveRequestHeader= Cookie,Set-Cookie


management:
  endpoints:
    web:
      exposure:
        include: "*"
